### ISSUE TITLE
Modo responsive problemas de estilos CSS

### ISSUE THREAD

**Issue by FeliPrado31** [CrisKop/moonie#1]
Hay un espacio al utilizar el responsive abajo del input para enviar mensajes

![image](https://github.com/CrisKop/moonie/assets/55117998/aa4ca60c-a1bd-42d1-9dec-e35900fe44f0)

**Comment by CrisKop** [comment]
Ya está arreglado, gracias por reportar el problema, cualquier sugerencia o error no dudes en reportarlo de nuevo! ❤️

https://github.com/CrisKop/moonie/compare/847df207bd13bf3b5004b287cbb9e0af4a5a0172...6650b5ca2778324e50db928f7db52549722e5d92
